const api = {
	// 订单列表
	ORDER_MAIN_ALL_GET: '',
	ORDER_MAIN_ALL_LIST_GET: '/test',
	ORDER_MAIN_ALL_DETAIL_GET: '',

	// 批量发货
	ORDER_BATCH_GET: '',

	// 售后
	ORDER_AFTER_SALE_GET: '',
	ORDER_AFTER_SALE_LIST_GET: '/test',
	ORDER_AFTER_SALE_DETAIL_GET: '',

	// 基础设置
	_ORDER_SETTING_BASIC_GET: '',
	_ORDER_SETTING_BASIC_SAVE_POST: '',

	// 运费模板
	ORDER_SETTING_TEMPLATE_GET: '',
	ORDER_SETTING_TEMPLATE_LIST_GET: '/test',

	// 包邮
	ORDER_SETTING_POSTAGE_GET: '',
	
	// 物流设置
	ORDER_SETTING_LOGISTICS_LIST_GET: '/test',
	_ORDER_SETTING_LOGISTICS_ADD_POST: '',
	_ORDER_SETTING_LOGISTICS_EDIT_POST: '',
	_ORDER_SETTING_LOGISTICS_CHANGE_STATUS_POST: '',
	_ORDER_SETTING_LOGISTICS_SET_DEFAULT_GET: '',
	_ORDER_SETTING_LOGISTICS_DELETE_POST: '',

	// 自提点
	ORDER_SETTING_SELF_ADDR_GET: '',
	ORDER_SETTING_SELF_ADDR_LIST_GET: '/test',
};
export default api;
