const api = {
	/**
	 * 请注释模块内容
	 */
	ORDER_BATCH_GET: '',
	ORDER_AFTER_SALE_GET: '',
	ORDER_AFTER_SALE_LIST_GET: '/test',
	ORDER_AFTER_SALE_DETAIL_GET: '',
	ORDER_MAIN_ALL_GET: '',
	ORDER_MAIN_ALL_LIST_GET: '/test',
	ORDER_MAIN_ALL_DETAIL_GET: '',
	ORDER_SETTING_BASIC_GET: '',
	ORDER_SETTING_TEMPLATE_GET: '',
	ORDER_SETTING_TEMPLATE_LIST_GET: '/test',
	ORDER_SETTING_POSTAGE_GET: '',
	
	ORDER_SETTING_LOGISTICS_LIST_GET: '/test',
	_ORDER_SETTING_LOGISTICS_ADD_POST: '',
	_ORDER_SETTING_LOGISTICS_EDIT_POST: '',
	_ORDER_SETTING_LOGISTICS_CHANGE_STATUS_POST: '',
	_ORDER_SETTING_LOGISTICS_SET_DEFAULT_GET: '',
	_ORDER_SETTING_LOGISTICS_DELETE_POST: '',

	ORDER_SETTING_SELF_ADDR_GET: '',
	ORDER_SETTING_SELF_ADDR_LIST_GET: '/test',
};
export default api;
