const api = {
	// 商品分类
	PRODUCT_CATEGORY_GET: '',
	PRODUCT_CATEGORY_LIST_GET: '/test',
	_PRODUCT_CATEGORY_GET_CHILD_GET: '',
	_PRODUCT_CATEGORY_DELETE_POST: '',
	_PRODUCT_CATEGORY_EDITOR_GET: '',
};
export default api;
