const api = {
	// 商品分类
	PRODUCT_CATEGORY_GET: '',
	PRODUCT_CATEGORY_LIST_GET: '/test',
	_PRODUCT_CATEGORY_GET_CHILD_GET: '',
	_PRODUCT_CATEGORY_DELETE_POST: '',
	_PRODUCT_CATEGORY_EDITOR_GET: '',

	// 商品新增 TODO: tpl 模板内的是2级路由，如果项目是三级，请自行修改
	PRODUCT_GOODS_EDITOR_GET: '',
	_PRODUCT_GOODS_EDITOR_SPEC_LIST_GET: '', // 获取下拉框规格数据
	_PRODUCT_GOODS_EDITOR_SPEC_VALUE_GET: '', // 获取规格值
	_PRODUCT_GOODS_EDITOR_SPEC_VALUE_DELETE_POST: '', // 删除规格值
	_PRODUCT_GOODS_EDITOR_SPEC_VALUE_ADD_POST: '', // 增加规格值
	_PRODUCT_GOODS_EDITOR_SPEC_ADD_POST: '', // 新增规格
	_PRODUCT_GOODS_EDITOR_SPEC_DELETE_POST: '', // 删除规格
	_PRODUCT_GOODS_EDITOR_SPEC_SORT_POST: '', // 规格排序管理
	_PRODUCT_GOODS_EDITOR_SKU_SN_EXIST_POST: '', // 当前货号是否存在
};
export default api;
